### ISSUE TITLE
Permission issue

### ISSUE THREAD

**Issue by Xidle** [AdvancedPlugins/Chat#27] opened 2024-04-22 18:55 UTC
### Describe the bug

When I set someone’s permission to advancedchat.Chatcolor.aqua it gets rid of the nopermission message but when clicked on it says in chat no permission to use this? I’ve tried giving the permissions with advancedchat.color.aqua and others. What is wrong here?

### How to reproduce

Advancedchat.chatcolor.aqua
Still no permission

**Comment by ThomasWega** [comment] 2024-04-25 18:22
Hey! We need a better explanation of what you're trying to achieve. Do you mind sending a short video showcase?

**Comment by heykiditsaaron** [comment] 2024-04-25 20:03
What he's trying to achieve is to have the permissions actually allow you to set a chatcolor per member. Even with permissions (eg: AdvancedChat.chatcolor.white) the player can see in the menu that the color is available, but when they click on it (demonstrated in the other post below), the server tells you that the player does not have that permission.

**Comment by ThomasWega** [comment] 2024-04-25 20:18
So you'd like to only show available colors in the menu?

**Comment by heykiditsaaron** [comment] 2024-04-25 20:25
That would be nice, but the issue is that in the menu NO ONE, even if they have the permissions, can actually use the chatcolor. If you assign them a permission, once they click on it they get a notice that says "You do not have permission to use this"

**Comment by ThomasWega** [comment] 2024-04-25 20:27
I'll test it out. Leaving the other suggestion as Feature Request

**Comment by heykiditsaaron** [comment] 2024-04-25 20:57
https://github.com/AdvancedPlugins/Chat/assets/55932658/004ae4fb-9a01-4790-8d7f-9d88ee64c792

**Comment by heykiditsaaron** [comment] 2024-04-25 21:18
It should be noted that this is AdvancedChat v1.0.6

**Comment by ThomasWega** [comment] 2024-05-06 07:21
Thank you for the video. Will look into this asap

**Comment by ThomasWega** [comment] 2024-05-18 12:14
Will be fixed next update! Apologies for the delay

**Closed by ThomasWega** 2024-05-18 12:14 UTC
Labels: Bug: Confirmed, Status: In development, Type: Feature Request
