### ISSUE TITLE
[item] doesn't work

### ISSUE THREAD

**Issue by MonsterMilo** [AdvancedPlugins/Chat#150] opened 2024-07-23 21:20 UTC
### Describe the bug

When typing [item] this error is sent console, the chat format is reset to default (for only that message), and it doesn't show the item when you hover over it.
Console error - https://mcpaste.io/dab038c456b6b7cf

### How to reproduce

1. Install AdvancedChat
2. Type [item]
3. The bug will occur

### Screenshots / Videos

Image with format reset - ![image](https://github.com/user-attachments/assets/78f57c80-de35-4ee3-92aa-3718310f0e1f)
Image with format correct (Rank is a symbol because texture pack hasn't loaded) ![image](https://github.com/user-attachments/assets/4baf4314-cd5c-47bf-9797-9d9d1f8d1fe1)

### Server Log

https://mcpaste.io/740465bcdc8f8eee

**Comment by ThomasWega** [comment] 2024-07-28 09:35
duplicate of https://github.com/AdvancedPlugins/Chat/issues/120

**Closed by ThomasWega** 2024-07-28 09:35 UTC
Labels: Bug: Unconfirmed
