### ISSUE TITLE
Double Cross Server Message Bug

### ISSUE THREAD

**Issue by L8-Alphine** [AdvancedPlugins/Chat#191] opened 2024-09-15 20:50 UTC
### Describe the bug

The bug is when I type a `crossServer: true` enabled channel like staff chat it sends a double message which is quite annoying.

### How to reproduce

Enable `crossServer` feature by changing `crossServer: false` to `crossServer: true` and type in that channel while it's connected and live on both servers.

### Screenshots / Videos

![image](https://github.com/user-attachments/assets/167fe68f-62b9-45c8-a5ca-87212e6a406e)

**Comment by ThomasWega** [comment] 2024-09-17 08:52
duplicate of https://github.com/AdvancedPlugins/Chat/issues/183. Will be taking a look into it

**Closed by ThomasWega** 2024-09-17 08:52 UTC
Labels: Bug: Unconfirmed
