### ISSUE TITLE
[item] doesn't show the correct name of the item

### ISSUE THREAD

**Issue by urAirborne** [AdvancedPlugins/Chat#130] opened 2024-07-10 15:05 UTC
### Describe the bug

like in the Title, [item] doesn't show the correct itemname and stats.
Also in Discord SRV
![Bild_2024-07-10_170409128](https://github.com/AdvancedPlugins/Chat/assets/175234099/a261ab95-a094-42e3-82a5-af46c8b043ac)
![Bild_2024-07-10_170436984](https://github.com/AdvancedPlugins/Chat/assets/175234099/1b481673-3e0d-4d0a-ad37-ebab24d7d9a6)
![image](https://github.com/AdvancedPlugins/Chat/assets/175234099/7396b283-a748-4e29-b6c7-7617d3a9eb94)

### How to reproduce

Take a diamond sword, rename it and enter [item] in the chat

**Comment by ThomasWega** [comment] 2024-07-12 10:33
duplicate of https://github.com/AdvancedPlugins/Chat/issues/112. Working on a fix

**Closed by ThomasWega** 2024-07-12 10:33 UTC
Labels: Bug: Unconfirmed
