### ISSUE TITLE
bug in tag and chatcolor permissions

### ISSUE THREAD

**Issue by Rcorcho6** [AdvancedPlugins/Chat#28] opened 2024-04-22 20:32 UTC
### Describe the bug

All the necessary permissions are assigned to use /tags and /chatcolors and we select but in the chat it says you do not have permissions, even though we have all the permissions

### How to reproduce

when we try to select a chat tags and/or color

### Screenshots / Videos

![image](https://github.com/AdvancedPlugins/Chat/assets/86140264/4875d8ae-b2b5-42c4-b732-2936a37a372a)

**Comment by ThomasWega** [comment] 2024-04-25 18:23
Hey! What permissions are you trying out? What's your config? We need specific information, we cannot solve anything like this

**Comment by heykiditsaaron** [comment] 2024-04-25 21:39
For context

**Comment by ThomasWega** [comment] 2024-05-06 07:22
will close this as a duplicate of https://github.com/AdvancedPlugins/Chat/issues/27 and handle the issue there

**Closed by ThomasWega** 2024-05-06 07:22 UTC
Labels: Status: Awaiting Response, Status: Lacking Critical Information, Bug: Unconfirmed
