### ISSUE TITLE
Ability to change username

### ISSUE THREAD

**Issue by Taiyou06** [AdvancedPlugins/Chat#201] opened 2024-10-05 18:22 UTC
### Describe the feature

Pretty self explanatory, `/chat rename <gold>player_name</gold>` type command to change username color as well as name.

**Comment by ThomasWega** [comment] 2024-10-05 20:49
duplicate of https://github.com/AdvancedPlugins/Chat/issues/185

**Closed by ThomasWega** 2024-10-05 20:49 UTC
Labels: Type: Feature Request
