### ISSUE TITLE
variables [item]

### ISSUE THREAD

**Issue by Tolmwn** [AdvancedPlugins/Chat#113] opened 2024-06-26 12:09 UTC
### Describe the bug

The bug about this is that when player use the [item] at the chat is not showing the name color or raname item and plus is not showing the enchant and lore that the item has. 

### How to reproduce

For example this here is my pickaxe and is be showing like that. I send you and a screenshot how must look.

![image](https://github.com/AdvancedPlugins/Chat/assets/136921445/3c644786-0989-4745-848f-b3f16287f2ad)
![image](https://github.com/AdvancedPlugins/Chat/assets/136921445/d322464c-6717-4496-8745-b45723218ea9)

### Server Log

https://mcpaste.io/1f27d004ec9fe2cc

**Comment by ThomasWega** [comment] 2024-06-26 18:41
Duplicate of https://github.com/AdvancedPlugins/Chat/issues/112

**Closed by ThomasWega** 2024-06-26 18:41 UTC
Labels: Bug: Confirmed

**Comment by Tolmwn** [comment] 2024-06-26 18:58
Its gonna be a new version now with the fixed [item] ?

**Comment by ThomasWega** [comment] 2024-06-26 19:23
When the other issue is solved

**Comment by Tolmwn** [comment] 2024-06-26 20:00
okey thanks
