### ISSUE TITLE
DiscordSRV Support

### ISSUE THREAD

**Issue by Xqow** [AdvancedPlugins/Chat#36] opened 2024-04-27 12:25 UTC
### Describe the bug

I am not fully sure if this is a bug or just an issue on my end, but it seems like that AdvancedChat fully breaks the minecraft -> discord chat bridge supplied by discordsrv. In the discord channel it no longer sends any chat messages from the minecraft server.

### How to reproduce

Install DiscordSRV on a server, set it up, type a message on the server: It should show up, but does not.

**Comment by ThomasWega** [comment] 2024-04-28 09:18
duplicate of https://github.com/AdvancedPlugins/Chat/issues/18

**Closed by ThomasWega** 2024-04-28 09:18 UTC
Labels: Bug: Unconfirmed
